---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: nexus
  name: nexus-1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 7Gi
