---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexuspv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/nexus"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexuspvc
  namespace: nexus
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: nexuspv
  resources:
    requests:
      storage: 2Gi
  
