---
apiVersion: v1
kind: Namespace
metadata:
  name: ansible
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-namespace
  namespace: ansible
automountServiceAccountToken: true
---
apiVersion: v1
kind: Secret
metadata:
  namespace: ansible
  name: namespace-create
  annotations:
    kubernetes.io/service-account.name: create-namespace
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-create
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-create
subjects:
- kind: ServiceAccount
  name: create-namespace
  namespace: ansible
roleRef:
  kind: ClusterRole
  name: namespace-create
  apiGroup: rbac.authorization.k8s.io
