---
apiVersion: v1
kind: Namespace
metadata:
  name: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mysql
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec: 
      containers:
      - name: mysql
        image: mysql
        ports:
          - containerPort: 8080
            name: default
          - containerPort: 1433
            name: specific
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: eight
---
---
apiVersion: v1
kind: Service
metadata:
  namespace: mysql
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - port: 1433
    protocol: TCP
    name: default
  - port: 8080
    protocol: TCP
    name: mysql
  selector:
    app: mysql
  type: NodePort
